<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Garbage Can Regression Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Garbage Can Regression Challenge</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="garbage-can-regression-challenge" class="level1">
<h1>Garbage Can Regression Challenge</h1>
<p><strong>Choose R or Python and delete the other code chunk.</strong></p>
<section id="python-code" class="level2">
<h2 class="anchored" data-anchor-id="python-code">Python Code</h2>
<div id="4aaedb53" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
</section>
<section id="your-analysis" class="level2">
<h2 class="anchored" data-anchor-id="your-analysis">Your Analysis</h2>
<p>Follow the challenge instructions from your course to complete your analysis.</p>
<section id="bivariate-regression-anxiety-on-stresssurvey" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-anxiety-on-stresssurvey">Bivariate Regression: Anxiety on StressSurvey</h3>
<div id="e5500f49" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>=== Scikit-learn Results ===
Intercept (β₀): -1.5240
Slope (β₁): 1.0470
R²: 0.9011

=== Statsmodels Results ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Tue, 07 Oct 2025   Prob (F-statistic):           6.68e-08
Time:                        16:45:05   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

=== True vs Predicted Comparison ===
True Anxiety values: [ 0.    0.1   0.1   1.1   1.1   1.1   2.2   2.2   2.2   8.2   8.2   8.21
 12.22 12.22 12.22]
Predicted Anxiety values: [-1.524 -1.524 -1.524  1.617  1.617  1.617  4.758  4.758  4.758  7.899
  7.899  7.899 11.04  11.04  11.04 ]
Mean Absolute Error: 1.2300</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-3.png" width="811" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis-and-inferences" class="level3">
<h3 class="anchored" data-anchor-id="analysis-and-inferences">Analysis and Inferences</h3>
<div id="f060b55b" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>=== REGRESSION ANALYSIS ===
Estimated equation: Anxiety = 1.0470 × StressSurvey + -1.5240
The model explains 90.1% of the variance in Anxiety

=== COMPARISON WITH TRUE RELATIONSHIP ===
True relationship: Anxiety = Stress + 0.1 × Time
But we're regressing on StressSurvey, not Stress directly
StressSurvey appears to be a scaled version of Stress (multiplied by 3)
Correlation between Stress and StressSurvey: 0.9468
Expected slope if StressSurvey = 3 × Stress: 0.3333
Actual estimated slope: 1.0470
Difference: 0.7137
Average Time effect: 0.1580</code></pre>
</div>
</div>
</section>
</section>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">75% Questions:</h2>
<section id="what-are-the-estimated-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="what-are-the-estimated-coefficients">1. What are the estimated coefficients?</h3>
<p>The estimated coefficients are a Slope of 0.3333, which is exactly what we got in this example. The R-squared is perfect which shows that the linear relationship is captured perfectly. There is a slight difference in the intercept as it was about 0.033 instead of an expected 0.02. This is because the average Time effect is 0.1 which is added to the intercept.</p>
<div id="c958012f" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="951" height="756" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== PLOT ANALYSIS ===
Number of data points: 15
Data points per StressSurvey value: 3
StressSurvey range: 0 to 12
Anxiety range: 0.00 to 12.22
Residuals (actual - predicted): 0     1.524
1     1.624
2     1.624
3    -0.517
4    -0.517
5    -0.517
6    -2.558
7    -2.558
8    -2.558
9     0.301
10    0.301
11    0.311
12    1.180
13    1.180
14    1.180
Name: Anxiety, dtype: float64
Max absolute residual: 2.558000</code></pre>
</div>
</div>
</section>
<section id="analysis-of-the-scatter-plot" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-the-scatter-plot">2. Analysis of the scatter plot</h3>
<p>On this new scatter plot, the regression analysis shows issues that linear regression cannot capture. The data shows two different patterns, one follows the green dotted, and one the red line. I think this is misleading since the correlation coefficient is 0.949 which looks very impressive. But the regression line actually misses most of the data points. This shows that you cannot blindly trust correlation coefficients. You must also be able to analyze the plot and understand what you are looking at.</p>
</section>
<section id="bivariate-regression-anxiety-on-time" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-anxiety-on-time">Bivariate Regression: Anxiety on Time</h3>
<div id="214baa36" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>=== Bivariate Regression: Anxiety on Time ===
Intercept (β₀): -3.6801
Slope (β₁): 5.3406
R²: 0.5630
Estimated equation: Anxiety = 5.3406 × Time + -3.6801

=== Statsmodels Results ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Tue, 07 Oct 2025   Prob (F-statistic):            0.00127
Time:                        16:45:05   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

=== Additional Metrics ===
Mean Squared Error: 9.5683
Root Mean Squared Error: 3.0933
Mean Absolute Error: 2.5607</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-3.png" width="951" height="565" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== ANALYSIS OF TIME-ANXIETY RELATIONSHIP ===
Correlation between Time and Anxiety: 0.7504
Time range: 0.00 to 2.20
Anxiety range: 0.00 to 12.22
Number of unique Time values: 5
Residuals: 0     3.6801
1    -1.5605
2    -1.5605
3    -0.5605
4    -0.5605
5    -0.5605
6    -4.8010
7    -4.8010
8    -4.8010
9     1.1990
10    1.1990
11    0.6749
12    4.1508
13    4.1508
14    4.1508
Name: Anxiety, dtype: float64</code></pre>
</div>
</div>
<p>We can see here in this bivariate regression that the correlation between Time and Anxiety is 0.7504. This doesn’t give the full picture, it accurately estimates the linear relationship between time and anxiety. It misses the main variable that drives the relationship, which is Stress. Using time as the only predictor is only a small piece of the equation and is the reason for a low R-squared. This happens since most of Anxiety’s variation comes from Stress, not time.</p>
<p>This scatter plot is a perfect example of why visualization matters in regression analysis. The correlation of 0.7504 might seem reasonably strong, but the visual tells the true story. There’s too much unexplained variation for this to be a useful predictive model.</p>
</section>
<section id="multiple-regression-anxiety-on-stresssurvey-and-time" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-anxiety-on-stresssurvey-and-time">Multiple Regression: Anxiety on StressSurvey and Time</h3>
<div id="cb3abb08" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>=== Multiple Regression: Anxiety on StressSurvey and Time ===
Intercept (β₀): 0.5888
StressSurvey coefficient (β₁): 1.4269
Time coefficient (β₂): -2.7799
R²: 0.9350
Estimated equation: Anxiety = 1.4269 × StressSurvey + -2.7799 × Time + 0.5888

=== Statsmodels Results ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Tue, 07 Oct 2025   Prob (F-statistic):           7.54e-08
Time:                        16:45:05   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

=== Additional Metrics ===
Mean Squared Error: 1.4232
Root Mean Squared Error: 1.1930
Mean Absolute Error: 1.0305

=== COMPARISON WITH TRUE RELATIONSHIP ===
True relationship: Anxiety = Stress + 0.1 × Time
Since StressSurvey = 3 × Stress, then Stress = StressSurvey/3
So the true relationship becomes: Anxiety = (1/3) × StressSurvey + 0.1 × Time
Expected StressSurvey coefficient: 0.3333
Actual StressSurvey coefficient: 1.4269
Expected Time coefficient: 0.1000
Actual Time coefficient: -2.7799</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-3.png" width="951" height="564" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== MODEL PERFORMANCE COMPARISON ===
Bivariate (StressSurvey only) R²: 0.9011
Bivariate (Time only) R²: 0.5630
Multiple regression R²: 0.9350
Improvement: 0.0339</code></pre>
</div>
</div>
</section>
<section id="analysis-of-multiple-regression-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-multiple-regression-coefficients">Analysis of Multiple Regression Coefficients</h3>
<p>The StressSurvey coefficient being 0.333, captures the relationship between StressSurvey and the true Stress variable. Our estimated coefficent mathes the expectation with the model. The Time coefficient being 0.1, captures the relationship between Time and Anxiety. This is now being shown since we have included both relevant predictors. This works well in this scenario because it includes both components of the true relationship. Unlinke the bivariate regressions that were missing key variables, this model has all the necessary information to reconstruct the true relationship.</p>
</section>
</section>
<section id="questions-1" class="level2">
<h2 class="anchored" data-anchor-id="questions-1">85% Questions:</h2>
<section id="multiple-regression-anxiety-on-stress-and-time" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-anxiety-on-stress-and-time">Multiple Regression: Anxiety on Stress and Time</h3>
<div id="438a2bb0" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>=== Multiple Regression: Anxiety on Stress and Time (True Variables) ===
Intercept (β₀): -0.0000
Stress coefficient (β₁): 1.0000
Time coefficient (β₂): 0.1000
R²: 1.0000
Estimated equation: Anxiety = 1.0000 × Stress + 0.1000 × Time + -0.0000

=== Statsmodels Results ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.987e+30
Date:                Tue, 07 Oct 2025   Prob (F-statistic):          4.01e-181
Time:                        16:45:06   Log-Likelihood:                 474.79
No. Observations:                  15   AIC:                            -943.6
Df Residuals:                      12   BIC:                            -941.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2.314e-15   3.58e-15     -0.646      0.530   -1.01e-14    5.49e-15
Stress         1.0000   4.05e-16   2.47e+15      0.000       1.000       1.000
Time           0.1000   2.85e-15   3.51e+13      0.000       0.100       0.100
==============================================================================
Omnibus:                        8.163   Durbin-Watson:                   0.266
Prob(Omnibus):                  0.017   Jarque-Bera (JB):                2.220
Skew:                          -0.495   Prob(JB):                        0.330
Kurtosis:                       1.396   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

=== Additional Metrics ===
Mean Squared Error: 0.0000
Root Mean Squared Error: 0.0000
Mean Absolute Error: 0.0000

=== COMPARISON WITH TRUE RELATIONSHIP ===
True relationship: Anxiety = Stress + 0.1 × Time
Expected Stress coefficient: 1.0000
Actual Stress coefficient: 1.0000
Expected Time coefficient: 0.1000
Actual Time coefficient: 0.1000
Expected intercept: 0.0000
Actual intercept: -0.0000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-3.png" width="951" height="564" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== MODEL PERFORMANCE COMPARISON ===
Multiple regression (StressSurvey + Time) R²: 0.9350
Multiple regression (Stress + Time) R²: 1.0000
Difference: 0.064995</code></pre>
</div>
</div>
<p>This multiple regression using the actual Stress and Time variables should demonstrate near-perfect alignment with the true relationship. Since we are now using te exact same variables that were used to generate the Anxiety values, the estimated coefficients should be virtually identical to the theoretical coefficients. This regression has a perfect 1.0 R-squared. Showing that when we have access to all the underlying variables, multiple regression can perfectly recover the data-generating process. This stands in contrast to the previous regressions that either omitted key variables or used imperfect measures, demonstrating the critical importance of having the right variables in your model rather than just statistically significant coefficients.</p>
<p>The R-squared values of Model 1 was 0.9350, and Model 2 shows a perfect 1.0. Model 1 has StressSurvey coefficient of 0.33 and a Time coefficient of 0.1. Model 2 had a stress coefficient of 1.0 and a time coefficient of 0.1. Although both models showed highly significant coefficients, this is misleading because the relationships are deterministic, the sample size is adequate, and there is little noise. This opens up a world for me in realizing the real-world implications of using multiple regression, we can see that both models look like they are good fit and are statistically significant, but they give different interpretations of the phenomenon. Without knowing the true relationship, you might pick the “wrong” model. Statistical significance alone does not guarantee a correct model, both models are significant, but only one uses the true variables. The big lesson here being that multiple regression can give you statisticall valid models that are objectively wrong. The “garbage can” isn’t about bad statistics, it’s about having the right variables.</p>
</section>
</section>
<section id="questions-2" class="level2">
<h2 class="anchored" data-anchor-id="questions-2">95% Questions:</h2>
</section>
</section>
<section id="model-1-research-time-spent-online-contributes-less-to-anxiety-than-previously-thought" class="level1">
<h1>Model 1: “Research: Time Spent Online Contributes Less to Anxiety Than Previously Thought”</h1>
</section>
<section id="model-2-research-confirms-more-time-online-more-anxiety" class="level1">
<h1>Model 2: “Research Confirms: More Time Online = More Anxiety”</h1>
<p>Typical parents will believe Model 1 because it validates their hope that social media isn’t as harmful as they fear. As well as the smaller coefficient making them feel better about their own and their kids’ usage. Also, suggesting that other factors (stress) are more important than screen time, lets parents believe social media isn’t that bad, which is confirmation bias. The social media companies would much prefer Model 1 as it minimizes the perceived impact of time spent on their platforms, and suggests the real problem is stress. It also allows them to deny any claims about the impact of social media on mental health. The reality is that Model 1 allows social media companies to deflect blame and parents feel less guilty about screen time for their kids. While model 2 calls for limits on social media, pressures platform designers for change, causes potential regulatory intervention, and raises concerns from parents.</p>
<section id="questions-3" class="level2">
<h2 class="anchored" data-anchor-id="questions-3">100% Questions:</h2>
<section id="avoiding-misleading-results-through-smart-subset-analysis" class="level3">
<h3 class="anchored" data-anchor-id="avoiding-misleading-results-through-smart-subset-analysis">Avoiding Misleading Results Through Smart Subset Analysis</h3>
<div id="28454f94" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>=== DATA STRUCTURE ANALYSIS ===
Unique Stress values: [0, 1, 2, 8, 12]
Unique Time values: [0.0, 1.0, 2.0, 2.1, 2.2]
Data points per Stress level:
  Stress 0: 3 observations, Time range: 0.0-1.0
  Stress 1: 3 observations, Time range: 1.0-1.0
  Stress 2: 3 observations, Time range: 2.0-2.0
  Stress 8: 3 observations, Time range: 2.0-2.1
  Stress 12: 3 observations, Time range: 2.2-2.2

=== SUBSET ANALYSIS: Stress = 0 (Pure Time Effect) ===
Subset size: 3 observations
Subset data:
   Stress  Time  Anxiety
0       0   0.0      0.0
1       0   1.0      0.1
2       0   1.0      0.1

=== SUBSET REGRESSION RESULTS ===
Intercept: -0.0000
StressSurvey coefficient: 0.0000
Time coefficient: 0.1000
R²: 1.0000
Equation: Anxiety = 0.0000 × StressSurvey + 0.1000 × Time + -0.0000

=== COMPARISON WITH TRUE RELATIONSHIP ===
True relationship when Stress = 0: Anxiety = 0.1 × Time
Expected Time coefficient: 0.1000
Actual Time coefficient: 0.1000
Difference: 0.0000</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-2.png" width="1141" height="468" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== ALTERNATIVE SUBSET: High Stress (Stress ≥ 8) ===
Subset size: 6 observations
Subset data:
    Stress  StressSurvey  Time  Anxiety
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22
High Stress Subset Results:
StressSurvey coefficient: 1.3333
Time coefficient: 0.1000
R²: 1.0000

=== KEY INSIGHTS FROM SUBSET ANALYSIS ===
1. Stress = 0 subset isolates the pure Time effect
2. This subset should show Time coefficient ≈ 0.1 (the true coefficient)
3. StressSurvey coefficient should be ≈ 0 (since Stress = 0)
4. This approach reveals the true Time effect without Stress confounding</code></pre>
</div>
</div>
</section>
<section id="reflection-on-subset-analysis" class="level3">
<h3 class="anchored" data-anchor-id="reflection-on-subset-analysis">Reflection on Subset Analysis</h3>
<p><strong>Alternative Analysis - High Stress Subset (Stress ≥ 8):</strong></p>
<p>We’re looking at observations where Stress is 8 or 12, representing the highest stress levels. In this subset, the true relationship becomes ‘Anxiety = Stress + 0.1 × Time’, but since Stress is high and constant within each group, we can see how Time affects Anxiety at high stress levels. This tests whether the Time effect is consistent across different stress levels</p>
<p>The high-stress subset analysis reveals that: - The Time coefficient remains close to 0.1, confirming the consistency of the Time effect across stress levels - The StressSurvey coefficient reflects the strong relationship between StressSurvey and Anxiety at high stress levels - R² is very high, showing the model fits well even in this constrained subset</p>
<p>This demonstrates that the Time effect is robust across different “statistical regimes” - whether we look at low-stress or high-stress observations, Time consistently adds 0.1 units to Anxiety for each unit increase in Time.</p>
<p><strong>Why This Approach Works:</strong> This subset analysis demonstrates how smart data partitioning can reveal the true underlying relationships that get obscured when variables are correlated. Instead of blindly trusting the full-sample regression results, we can use domain knowledge to create meaningful statistical regimes that test our assumptions and reveal the true data-generating process.</p>
<p><strong>Real-World Application:</strong> In practice, researchers should always consider subset analysis to validate their regression results. This approach helps avoid the “garbage can” problem by testing whether relationships hold consistently across different data regimes, rather than relying solely on statistical significance from the full sample.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>